import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:share_plus/share_plus.dart';

import '../../../providers/auth_provider.dart';
import '../../../providers/database_provider.dart';
import '../../theme/app_colors.dart';

/// Screen to share a trip invite via QR code, link, or 6-char code.
///
/// When [isNewTrip] is true (navigated from CreateTripScreen), shows a
/// celebration header and the "Enter the trip →" button instead of a
/// plain back arrow, so the admin has a clear path into the trip after
/// sharing.  An [initialCode] can be passed to skip regeneration.
class InviteScreen extends ConsumerStatefulWidget {
  final String tripId;
  final String tripName;

  /// Set to true when arriving directly from trip creation.
  final bool isNewTrip;

  /// Pre-generated code from CreateTripScreen — avoids creating a duplicate.
  final String? initialCode;

  const InviteScreen({
    super.key,
    required this.tripId,
    required this.tripName,
    this.isNewTrip = false,
    this.initialCode,
  });

  @override
  ConsumerState<InviteScreen> createState() => _InviteScreenState();
}

class _InviteScreenState extends ConsumerState<InviteScreen>
    with TickerProviderStateMixin {
  String? _inviteCode;
  bool _isGenerating = false;
  late AnimationController _pulseController;
  late Animation<double> _pulseAnimation;

  // Entry animation for the new-trip celebration.
  late AnimationController _entryController;
  late Animation<double> _entryFade;
  late Animation<Offset> _entrySlide;

  @override
  void initState() {
    super.initState();

    _pulseController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 1500),
    )..repeat(reverse: true);
    _pulseAnimation = Tween<double>(begin: 0.97, end: 1.03).animate(
      CurvedAnimation(parent: _pulseController, curve: Curves.easeInOut),
    );

    _entryController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 600),
    );
    _entryFade = CurvedAnimation(
      parent: _entryController,
      curve: Curves.easeOut,
    );
    _entrySlide = Tween<Offset>(
      begin: const Offset(0, 0.06),
      end: Offset.zero,
    ).animate(CurvedAnimation(parent: _entryController, curve: Curves.easeOut));

    if (widget.initialCode != null) {
      // Code already generated by CreateTripScreen — use it directly.
      _inviteCode = widget.initialCode;
      _entryController.forward();
    } else {
      _generateInvite();
    }
  }

  @override
  void dispose() {
    _pulseController.dispose();
    _entryController.dispose();
    super.dispose();
  }

  Future<void> _generateInvite() async {
    setState(() => _isGenerating = true);
    try {
      final db = ref.read(databaseProvider);
      final currentUser = ref.read(currentUserProvider);
      if (currentUser == null) return;

      final code = await db.tripInvitesDao.createInvite(
        tripId: widget.tripId,
        createdBy: currentUser.id,
      );
      if (mounted) {
        setState(() => _inviteCode = code);
        _entryController.forward(from: 0);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to create invite: $e',
                style: GoogleFonts.inter()),
            backgroundColor: AppColors.error,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isGenerating = false);
    }
  }

  String get _shareLink => 'https://triptab.app/join/$_inviteCode';

  void _copyCode() {
    if (_inviteCode == null) return;
    Clipboard.setData(ClipboardData(text: _inviteCode!));
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text('Code copied!', style: GoogleFonts.inter()),
        backgroundColor: AppColors.success,
        behavior: SnackBarBehavior.floating,
        duration: const Duration(seconds: 2),
      ),
    );
  }

  void _share() {
    if (_inviteCode == null) return;
    SharePlus.instance.share(
      ShareParams(
        text:
            'Join my trip "${widget.tripName}" on TripTab!\n\nUse code: $_inviteCode\n\nOr tap: $_shareLink',
        subject: 'Join ${widget.tripName} on TripTab',
      ),
    );
  }

  void _enterTrip() => context.go('/trip/${widget.tripId}');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        // New-trip flow: back goes to the trip, not the create screen.
        leading: widget.isNewTrip
            ? IconButton(
                icon: const Icon(Icons.arrow_forward_rounded),
                tooltip: 'Enter trip',
                onPressed: _enterTrip,
              )
            : null,
        title: Text(
          widget.isNewTrip ? 'Share with your group' : 'Invite People',
          style: GoogleFonts.inter(fontWeight: FontWeight.w700),
        ),
        actions: [
          if (!widget.isNewTrip)
            TextButton.icon(
              onPressed: _generateInvite,
              icon: const Icon(Icons.refresh_rounded, size: 18),
              label: Text('New code', style: GoogleFonts.inter(fontSize: 13)),
            ),
          if (widget.isNewTrip)
            TextButton(
              onPressed: _enterTrip,
              child: Text(
                'Enter trip →',
                style: GoogleFonts.inter(
                  fontWeight: FontWeight.w600,
                  color: AppColors.primary,
                ),
              ),
            ),
        ],
      ),
      body: _isGenerating
          ? const Center(
              child: CircularProgressIndicator(color: AppColors.primary))
          : _buildContent(),
    );
  }

  Widget _buildContent() {
    if (_inviteCode == null) {
      return Center(
        child: Text('Failed to generate invite.',
            style: GoogleFonts.inter(color: context.colorTextSecondary)),
      );
    }

    return FadeTransition(
      opacity: _entryFade,
      child: SlideTransition(
        position: _entrySlide,
        child: SingleChildScrollView(
          padding: const EdgeInsets.fromLTRB(24, 16, 24, 40),
          child: Column(
            children: [
              // ── New-trip celebration header ──────────────────────
              if (widget.isNewTrip) ...[
                Container(
                  padding: const EdgeInsets.symmetric(
                      horizontal: 20, vertical: 14),
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      colors: [
                        AppColors.primary.withValues(alpha: 0.15),
                        AppColors.primary.withValues(alpha: 0.05),
                      ],
                    ),
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(
                      color: AppColors.primary.withValues(alpha: 0.2),
                    ),
                  ),
                  child: Row(
                    children: [
                      const Text('🎉', style: TextStyle(fontSize: 28)),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Trip created! You\'re the admin.',
                              style: GoogleFonts.inter(
                                fontSize: 14,
                                fontWeight: FontWeight.w700,
                                color: context.colorTextPrimary,
                              ),
                            ),
                            const SizedBox(height: 2),
                            Text(
                              'Share the QR or code below so others can join.',
                              style: GoogleFonts.inter(
                                fontSize: 12,
                                color: context.colorTextSecondary,
                                height: 1.4,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 20),
              ] else ...[
                // ── Standard trip label ──────────────────────────
                Container(
                  padding: const EdgeInsets.symmetric(
                      horizontal: 14, vertical: 8),
                  decoration: BoxDecoration(
                    color: AppColors.primary.withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(20),
                  ),
                  child: Text(
                    widget.tripName,
                    style: GoogleFonts.inter(
                      fontWeight: FontWeight.w600,
                      color: AppColors.primary,
                      fontSize: 14,
                    ),
                  ),
                ),
                const SizedBox(height: 8),
                Text(
                  'Share any of the options below\nto invite someone to this trip',
                  textAlign: TextAlign.center,
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    color: context.colorTextSecondary,
                    height: 1.5,
                  ),
                ),
                const SizedBox(height: 32),
              ],

              // ── QR Code ─────────────────────────────────────────
              AnimatedBuilder(
                animation: _pulseAnimation,
                builder: (context, child) => Transform.scale(
                  scale: _pulseAnimation.value,
                  child: child,
                ),
                child: Container(
                  padding: const EdgeInsets.all(20),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(24),
                    boxShadow: [
                      BoxShadow(
                        color: AppColors.primary.withValues(alpha: 0.2),
                        blurRadius: 40,
                        offset: const Offset(0, 8),
                      ),
                    ],
                  ),
                  child: QrImageView(
                    data: _shareLink,
                    version: QrVersions.auto,
                    size: 200,
                    backgroundColor: Colors.white,
                    eyeStyle: const QrEyeStyle(
                      eyeShape: QrEyeShape.square,
                      color: Color(0xFF009688),
                    ),
                    dataModuleStyle: const QrDataModuleStyle(
                      dataModuleShape: QrDataModuleShape.square,
                      color: Color(0xFF1A1A2E),
                    ),
                  ),
                ),
              ),

              const SizedBox(height: 10),
              Text(
                'Scan with camera to join',
                style: GoogleFonts.inter(
                  fontSize: 12,
                  color: context.colorTextTertiary,
                ),
              ),

              const SizedBox(height: 28),

              // ── 6-char code ─────────────────────────────────────
              Text(
                'Or share the invite code',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: context.colorTextSecondary,
                  fontWeight: FontWeight.w500,
                ),
              ),
              const SizedBox(height: 12),

              GestureDetector(
                onTap: _copyCode,
                child: Container(
                  padding: const EdgeInsets.symmetric(
                      horizontal: 28, vertical: 16),
                  decoration: BoxDecoration(
                    color: context.colorCardBackground,
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(
                      color: AppColors.primary.withValues(alpha: 0.3),
                      width: 1.5,
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(
                        _inviteCode!,
                        style: GoogleFonts.inter(
                          fontSize: 32,
                          fontWeight: FontWeight.w800,
                          color: AppColors.primary,
                          letterSpacing: 8,
                        ),
                      ),
                      const SizedBox(width: 12),
                      Icon(
                        Icons.copy_rounded,
                        size: 20,
                        color: context.colorTextTertiary,
                      ),
                    ],
                  ),
                ),
              ),

              const SizedBox(height: 6),
              Text(
                'Tap to copy · Valid for 7 days · Up to 50 uses',
                style: GoogleFonts.inter(
                  fontSize: 11,
                  color: context.colorTextTertiary,
                ),
              ),

              const SizedBox(height: 28),

              // ── Share button ─────────────────────────────────────
              SizedBox(
                width: double.infinity,
                height: 52,
                child: ElevatedButton.icon(
                  onPressed: _share,
                  icon: const Icon(Icons.share_rounded, size: 20),
                  label: Text(
                    'Share Invite',
                    style: GoogleFonts.inter(
                      fontSize: 15,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColors.primary,
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(14),
                    ),
                    elevation: 0,
                  ),
                ),
              ),

              // ── Enter trip button (new-trip flow) ────────────────
              if (widget.isNewTrip) ...[
                const SizedBox(height: 12),
                SizedBox(
                  width: double.infinity,
                  height: 52,
                  child: OutlinedButton.icon(
                    onPressed: _enterTrip,
                    icon: const Icon(Icons.arrow_forward_rounded, size: 20),
                    label: Text(
                      'Enter Trip',
                      style: GoogleFonts.inter(
                        fontSize: 15,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                    style: OutlinedButton.styleFrom(
                      foregroundColor: AppColors.primary,
                      side: BorderSide(
                        color: AppColors.primary.withValues(alpha: 0.4),
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(14),
                      ),
                    ),
                  ),
                ),
              ],

              const SizedBox(height: 28),

              // ── How it works ─────────────────────────────────────
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: context.colorSurfaceVariant,
                  borderRadius: BorderRadius.circular(14),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'How joining works',
                      style: GoogleFonts.inter(
                        fontSize: 13,
                        fontWeight: FontWeight.w600,
                        color: context.colorTextSecondary,
                      ),
                    ),
                    const SizedBox(height: 10),
                    _step('1', 'They download TripTab & create an account'),
                    _step('2', 'Tap Join on the home screen'),
                    _step('3', 'Enter the code or scan QR'),
                    _step('4', 'Done — they\'re in the trip!'),
                  ],
                ),
              ),

              if (!widget.isNewTrip) ...[
                const SizedBox(height: 16),
                TextButton.icon(
                  onPressed: _generateInvite,
                  icon: const Icon(Icons.refresh_rounded, size: 16),
                  label: Text(
                    'Generate new code',
                    style: GoogleFonts.inter(fontSize: 13),
                  ),
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }

  Widget _step(String num, String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 6),
      child: Row(
        children: [
          Container(
            width: 20,
            height: 20,
            decoration: BoxDecoration(
              color: AppColors.primary.withValues(alpha: 0.15),
              shape: BoxShape.circle,
            ),
            child: Center(
              child: Text(
                num,
                style: GoogleFonts.inter(
                  fontSize: 11,
                  fontWeight: FontWeight.w700,
                  color: AppColors.primary,
                ),
              ),
            ),
          ),
          const SizedBox(width: 10),
          Expanded(
            child: Text(
              text,
              style: GoogleFonts.inter(
                fontSize: 13,
                color: context.colorTextSecondary,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
